### ISSUE TITLE
Error when running in Windows

### ISSUE THREAD

**Issue by ClausKjaerPedersen** [wbuchanan/eda#4]
Dear W. Buchanan
I encountered a error when running eda.ado in Windows 10 (STATA 15.1). I have used the example from "eda.sthlp": 
         sysuse auto.dta, clear
        eda, r(`"`c(pwd)'/edaexamples"') o("minexample") comp

The following error occurs when the program runs the "exec"-batch in PDFLATEX (MIKTEX):
![2018-06-22 08_37_38-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/40484978/41761906-38385b08-75f9-11e8-9deb-e737c5d9c213.png)

I have tried to remove the line: "\usepackage{fixltx2e}" (since it seemed that this were causing the error) from mineexample.tax, which then results in following error:

![2018-06-22 08_58_06-c__windows_system32_cmd_b](https://user-images.githubusercontent.com/40484978/41762266-81361fec-75fa-11e8-93ac-4a08162011c0.png)

I have updated Stata files and Miktex.

Best regards Claus Pedersen

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
I'm testing this now and in the process discovered a smaller issue that I think I also want to try to fix.  It seems that if the value passed to the `root` parameter is a directory that does not already exist the program will fail.  If nothing else, I think making the program handle that case to create the directory if needed would make things a bit easier.  The example is still running on one of the VMs I use at work, but at least wanted to let you know that I was testing things out.

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
Ok. I think I've figured out what the issue is.  It seems to be specific to Windows environments and how Windows uses escape sequences for path delimiters (e.g., using `\` to separate paths instead of `/`).  That said there is also something a bit odd happening with the way the batch file is generated that I'll need to try fixing/patching as well.  It shouldn't be too painful to fix things relatively quickly though.

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
I've pushed an updated version to the gh-pages branch of the repository so you should be able to update your version and go from there.  I've added a little to the package to manage some dependencies that exist in some other programs I've put together, but it should be a fairly minor change for most end users (e.g., the program will now check to make sure that [brewscheme](https://wbuchanan.github.io/brewscheme) is available on the user's system and offer to install it if it isn't).  If you could verify that this fixed things for you that would be great.

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
I just pushed an update and tested it on the machine at work.  Everything seems to work now with the exception of generating the command needed to shell out and run the Windows batch file.  That should be a relatively quick fix and if needed the batch file could be run manually at the moment.

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
I replaced the `end` in the section that checks for dependencies with `exit` and was able to run things successfully.  I just recently pushed an update for the generation of the command that would shell out to compile the LaTeX file.  I'll check things on the work machine again later this week, but if the newest version works for you please let me know.  It may be a bit difficult to get it to update, but you can use the force option to reinstall/update things if needed.

**Comment by ClausKjaerPedersen** [comment]
@wbuchanan 
I still get this error:
- dirfile `root', p("graphs") rebuild
  = dirfile C:/data, p("graphs") rebuild
    ------------------------------------------------------ begin dirfile ---
    - version 13
    - syntax , Path(string) [ REBuild ]
varlist not allowed
    -------------------------------------------------------- end dirfile ---
  -------------------------------------------------------------- end eda ---
r(101);
end of do-file
r(101);
***********************************************************************
When I change "dirfile `root', p("graphs")" rebuild" to "dirfile, p(`"`root'/graphs"') rebuild" and "dirfile `root', p("tables")" to "dirfile, p(`"`root'/tables"') rebuild" it works until  the shell out and run of the Windows batch file (see last part off results below).
The batch file is saved and named "makeLaTex..bat" (with two periods!), but it isn't executed. 
If when I run it with two periods in the name, it works!:
"! C:/data/makeLaTeX.bat" - doesn't work
"! C:/data/makeLaTeX..bat" - works!

Claus

*****************************************************************************
…
    ---------------------------------------------------- end maketexcomp ---
  - loc exec `r(comp)'
  = loc exec ! C:/data/makeLaTeX.bat
  - `exec'
  = ! C:/data/makeLaTeX.bat
  - }
  - restore
  -------------------------------------------------------------- end eda ---
. 
. 
end of do-file

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen
Did you uninstall and then reinstall `eda`?

You can use :

```Stata
ado, find(“eda”)
ado uninstall [#]
net inst eda, from(“http://wbuchanan.github.io/eda”) replace force
```

To make sure the version that you have is the most recently updated version.  I’ll uninstall and then install and run things from my work machine later this morning.  I’m not sure why you are getting some of the behavior that you’ve observed just yet.

Thanks again,
Billy

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
Just pushed a change that fixes the issue with the extra period in the file name that compiles the LaTeX document.  You should be able to use `ado update` to pull in the newest version.

**Comment by ClausKjaerPedersen** [comment]
Yes, I did. Just repeated it (and checked that all files were removed). I still get the same error. But as I mentioned, it works when I change: 
"dirfile `root', p("graphs")" rebuild" to "dirfile, p("root'/graphs"') rebuild" 
and 
"dirfile `root', p("tables")" to "dirfile, p("root'/tables"') rebuild"
I guess it is something with how paths are specified in Windows?

**Comment by ClausKjaerPedersen** [comment]
Sorry didn't see your latest message before I answered! I will just check it out!

**Comment by wbuchanan** [comment]
@ClausKjaerPedersen 
The version of `dirfile` that should be getting used now has a different syntax structure from:

```Stata
syntax, Path(string) [REBuild]
```
The most up to date version has a syntax command like this:

```Stata
syntax [anything(name = root id = "Root directory")], [ Path(string) REBuild ]
```

My guess is that it could be an old version of that program still cached in memory or something along those lines.

**Comment by ClausKjaerPedersen** [comment]
Latest version of brewscheme (which includes dirfile, right?) downloadable via STATA is  " Distribution-Date: 20160321"

**Comment by ClausKjaerPedersen** [comment]
the included dirfile.ado is version:		
*! dirfile
*! v 0.0.3
*! 04NOV2015

**Comment by ClausKjaerPedersen** [comment]
where can I get the update version?

**Comment by wbuchanan** [comment]
Easiest solution:

```Stata
ado, find(brewscheme)
ado uninstall [#]
ado, find(eda)
ado uninstall [#]
```
Substitute the number reported back from `ado, find()` where you see the `#`.  Then if you reinstall `eda` it will install the version of `brewscheme` that is available from GitHub : https://wbuchanan.github.io/brewscheme.

**Comment by ClausKjaerPedersen** [comment]
@wbuchanan 
IT WORKS!
Thank you very much for your patience!
It is indeed a brilliant program! 
Good luck at the conference - I am sure they will appreciate it just as much as I do!
Thank you!
Claus
